# Based on the matrix example recipe from actions-rs:
# https://github.com/actions-rs/meta/blob/master/recipes/matrix.md

name: Push Tests

on:
  push:
  schedule:
    - cron: 0 13 * * 1 # Every Monday at 1PM UTC (9AM EST)

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.60.0  # Minimum Supported Rust Version

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy, cargo-msrv

      - name: Check fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --release

      - name: Unit Tests
        run: cargo test --all-features

      - name: Minimum Supported Rust Version
        run: cargo msrv verify

      - name: "Example CLI: Check fmt"
        run: cd examples/cli && cargo fmt --all -- --check

      - name: "Example CLI: Clippy"
        run: cd examples/cli && cargo clippy -- -D warnings

      - name: "Example CLI: Build"
        run: cd examples/cli && cargo build --release

      - name: "Example CLI: Test"
        run: cd examples/cli && cargo test --all-features
